name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC every day
  workflow_dispatch:      # Allows manual triggering through GitHub UI

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Supabase Client
        run: npm install @supabase/supabase-js
      
      - name: Verify Supabase Client Installation
        run: npm list @supabase/supabase-js

      - name: Ping Supabase Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/keep-alive.js
